### ISSUE TITLE
Issue with very short mp3 files

### ISSUE THREAD

**Issue by Skeevy** [lieff/minimp3#102]
Hello,

I'm using this in a debug environment. It's working nice and efficient for most files, but I have problems with very short files. I've attached a sample file. In fact, the decoder only returns one frame with 1152 samples here. Could you please have a look? Thanks!
[Sample.zip](https://github.com/lieff/minimp3/files/9799732/Sample.zip)

**Comment by Skeevy** [comment]
I just investigated this recently and it turned out that files with a frame size below MAX_FRAME_SYNC_MATCHES won't be decoded. I've lowered this constant and can't see any downside so far, so this is now working for me.

**Comment by Joshua-Ashton** [comment]
My PR here https://github.com/lieff/minimp3/pull/125 likely solves the problem for you. I hit this with playing short sfx in a game.
