### ISSUE TITLE
Add some fuzzer lib test

### ISSUE THREAD

**Issue by lieff** [lieff/minimp3#11]
As suggested here https://github.com/hajimehoshi/go-mp3/issues/23#issuecomment-364003179
http://lcamtuf.coredump.cx/afl/ 
https://github.com/google/fuzzer-test-suite/blob/master/tutorial/libFuzzerTutorial.md

**Comment by sagamusix** [comment]
I have already fuzz-tested minimp3 a bit with afl (no crashes found so far ;), if you want I can provide the scripts / test code that I used.

**Comment by dgryski** [comment]
@sagamusix Does it make sense to file a PR with your tooling?

**Comment by lieff** [comment]
@sagamusix Sure, it will be extremely useful )

**Comment by sagamusix** [comment]
Okay, I will create a PR with the fuzzer stuff then. I currently don't have access to the computer I have the fuzzer setup stored on, but I should be able to do so within the next week.

**Comment by josephbisch** [comment]
@sagamusix I have also done a bit of fuzzing of minimp3. I suggest trying with Address Sanitizer if you haven't already.

**Comment by lieff** [comment]
Yes, I've already using asan & ubsan sanitizers.

**Comment by josephbisch** [comment]
Here is how I did it:

Compile:
```
afl-gcc -fsanitize=address,undefined -fno-sanitize-recover=address,undefined -o minimp3_test minimp3_test.c -lm
```
Then run afl-fuzz. I recommend using a small mp3 file as the initial input, such as the one at https://github.com/mathiasbynens/small.

Run:
```
afl-fuzz -m none -i in -o out -- ../minimp3_test @@
```

**Comment by sagamusix** [comment]
I did a bit more than just compiling the provided example because it has a lot of unnecessary code paths outside minimp3 that really do not need to be fuzzed. I'll provide that ASAP. Also, using afl-clang-fast is of course preferred.

**Comment by josephbisch** [comment]
I wasn't explicit why I was suggesting asan. It's because I'm getting out of bounds reads when fuzzing minimp3_test. They look like they are actually in minimp3.h rather than the example code. I don't know why you aren't getting them, but I am. Maybe they do have to do with one of those unnecessary code paths in the example code.

**Comment by lieff** [comment]
I've only use asan on test vectors base. With afl I'm getting crashes too, thanks @josephbisch :)

**Comment by lieff** [comment]
Ok, I fixed input over-read, and 0 crashes so far.

**Comment by josephbisch** [comment]
Are you using `-fno-sanitize-recover`? I tried the latest minimp3 with the fix you added. I ran the crashes through the minimp3_test program and some still caused ubsan errors. Maybe afl just isn't detecting the ubsan errors as a crash if you aren't using `-fno-sanitize-recover`?

**Comment by lieff** [comment]
Hmm, yes, I'm using exact `afl-gcc -fsanitize=address,undefined -fno-sanitize-recover=address,undefined -o minimp3_test minimp3_test.c -lm` line.

**Comment by josephbisch** [comment]
Oh, my mistake. It seems gcc doesn't support `-fno-sanitize-recover`, so minimp3_test should be built with afl-clang or afl-clang-fast.

**Comment by lieff** [comment]
May be version difference?
```
afl-cc 2.49b by <lcamtuf@google.com>                                        
gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0                                           
```

**Comment by lieff** [comment]
Wow, thanks again :) fixed in https://github.com/lieff/minimp3/commit/9acf26a2bec43b0ae01bb78505ce2b12c6d362ad

**Comment by lieff** [comment]
Few more ubsan fixes and no crashes in hours again.

**Comment by dgryski** [comment]
This can probably be closed.

**Comment by lieff** [comment]
Soon :) I'm still trying to find more bugs using both fuzzers.

**Comment by lieff** [comment]
Why in persistent mode stability is not 100%? Hmm..

**Comment by sagamusix** [comment]
I didn't encounter that in my tests, but I haven't fuzzed the latest revisions yet. It either means that the system is under load, or some paths rely on non-const static or uninitialized data.

**Comment by lieff** [comment]
Can't fuzz any more crashes.
