### ISSUE TITLE
Use LLVM-MCA tool to analyse performance issues

### ISSUE THREAD

**Issue by lieff** [lieff/minimp3#20]
http://lists.llvm.org/pipermail/llvm-dev/2018-March/121490.html

**Comment by lieff** [comment]
@acassis Hi :)
This is public domain license, according to this
https://www.gnu.org/licenses/license-list.en.html
>CC0 is a public domain dedication from Creative Commons. A work released under CC0 is dedicated to the public domain to the fullest extent permitted by law. If that is not possible for any reason, CC0 also provides a lax, permissive license as a fallback. Both public domain works and the lax license provided by CC0 are compatible with the GNU GPL.

>If you want to release your work to the public domain, we recommend you use CC0.

It's compatible with GPL, so it must be compatible with less restrictive BSD too.
I want this code to be as open as possible (and compatible with BSD/MIT etc), I'm not sure if https://unlicense.org better in this.

**Comment by acassis** [comment]
Hi Lion,

Thank you very much!

I 'm not sure as well if https://unlicense.org is better. IANAL, but I found some discussion about it here:
https://softwareengineering.stackexchange.com/questions/147111/what-is-wrong-with-the-unlicense

BTW, if you accept to release it as dual license, then we can use it as BSD license with NuttX! :-)

I will test minimp3 this weekend and to get it working. BR, Alan

**Comment by lieff** [comment]
https://github.com/Cyan4973/xxHash/issues/91#issuecomment-260935015
according to this comment BSD and MIT require attribution in binary form. It can confuse user in dual license case, what rules he must follow.
So I prefer to stay as simple as possible (without dual license or license change) while it's no real problem somewhere.

**Comment by acassis** [comment]
Hi Lion,
Yes, BSD and MIT enforce some attribution.

It is not clear to me as "public domain" CC0 license is.

Please check this: https://softwareengineering.stackexchange.com/questions/250259/does-cc0-allow-sublicensing-of-derived-works

It suggests that CC0 couldn't be sub-licensed and that unlicense allows sub-licensing.

This is his conclusion:
"If you have to check if CC0 is sub licensable or not, you don't use it. If you see a BSD license, you know what you can do with it."

So, maybe unlicense makes more sense. Sorry to raise these issue to you! I just want to use your code, but at end of day I don't want to bring issues to NuttX project caused by license conflict :-)

**Comment by lieff** [comment]
@acassis I'm pretty sure it can. Because public domain projects like SQLite and stb used as sub-projects without no-problem. You even do not to copy license file, usually people just only stb_image.h to project and that's it, license mentioned in header file itself. I want same behavior, It's very fitting for single header lib, you need to copy just one file. If it's not true - many many projects have problem.

**Comment by lieff** [comment]
@acassis Another example: https://github.com/ValyriaTear/ValyriaTear/blob/master/LICENSES.txt
GPL and different versions of CC in one project, absolutely no problem at all.

**Comment by acassis** [comment]
Thank you very much @lieff !
I contacted the NuttX author and explained about my idea, he explained this:

"It is always okay to re-release coding under a stronger license that still includes all of the requirements of the weaker license.  GPL is a super-set license that includes all of the requirements of CC0 and then a lot more.

BSD is a weaker license than CC0.  I would have to eliminate CC0 requirements.  That is forbidden and illegal.  I cannot re-release CC0 code under the BSD license without specific permission from the author to re-license as BSD and to acknowledge that they are removing requirements from the license."

Then I cannot use minimp3 code on NuttX without your permission.

**Comment by lieff** [comment]
@acassis I think he is wrong, BSD is stronger than CC0 https://freedomdefined.org/Licenses#Comparison_of_Licenses
It's even do not require any attribution, which BSD require.
Anyway, he have my permission re-license it under BSD if he wants. Is this message enough for this?

**Comment by lieff** [comment]
https://medium.com/shakuro/software-licenses-explained-77f4f18ebeb1
Another good explanation about licenses, and according to this CC0 is BSD compatible and I do not see any better variant to cover all permissive licenses.

**Comment by acassis** [comment]
Thank you for further explanation Lion. BTW, I think this message here is enough. BR, Alan

**Comment by lieff** [comment]
Great :)
Closing since issue title not more relevant to discussion.
