### ISSUE TITLE
Add optional high-level decode functions

### ISSUE THREAD

**Issue by lieff** [lieff/minimp3#27]
Reference implementations of how to decode file and memory block can be handy.
Plus seek index may be?

**Comment by lieff** [comment]
Decode/iterate functions done https://github.com/lieff/minimp3/blob/master/minimp3_ex.h
Indexed\raw seek is on the way.

**Comment by AlexanderZimin** [comment]
Appreciate your work! How to check validity of data?
I obtain data through http, users could send whatever. How can I check, that the data (buffer or file) is valid mp3?

**Comment by lieff** [comment]
@AlexanderZimin Reference vectors contains files with "garbage bytes" between frames. Also common case is "cutted" bit-reservoir. So in general case there no way to check if file completely valid or not. Best you can check if iterate function get some frames. It can be all good frames without garbage or with small amount of garbage (as reference vectors with garbage) or it can be few frames in big chunk of garbage. Iterate function should be bullet-proof and not crash on any invalid data otherwise this is bug.

**Comment by lieff** [comment]
All high-level functions implemented.
