### ISSUE TITLE
Questions about usage

### ISSUE THREAD

**Issue by rpvelloso** [lieff/minimp3#3]
Hello,

1) How can I seek to arbitrary positions? Let say to sample number 'N' (RAW decoded sample, that is)?
2) How can I initialize the 'info' without decoding any audio?

Thanks!

**Comment by lieff** [comment]
In general case seek is complex, frames can be different in size. This part of code tries to resync:
```
    if (!frame_size)
    {
        memset(dec, 0, sizeof(mp3dec_t));
        i = mp3d_find_frame(mp3, mp3_bytes, &dec->free_format_bytes, &frame_size);
        if (!frame_size || i + frame_size > mp3_bytes)
        {
            info->frame_bytes = i;
            return 0;
        }
    }
```
You can just seek to any byte in the middle of stream and call mp3dec_decode_frame, it works almost always, but not 100% guaranteed. If granule data accidentally detected as valid mp3 header, short audio artifacts is possible.

mp3dec_decode_frame always initialize info.frame_bytes, if it's nonzero, all info fields will be initialized too. At least one frame must be decoded to get info structure. Separate function to only sync to mp3 header and get info can be added, but it can be false-detected valid header.

**Comment by lieff** [comment]
About precise seek to sample number 'N': in general case it's not possible without full scan form beginning. It's possible if file known to be cbr and frames have equal size or stream encapsulated in some container and have index (index may not have sample accurate position too).

**Comment by rpvelloso** [comment]
yeah, I was reading about it, VBR complicates this. Thanks for the promptly reply, though.
