### ISSUE TITLE
Separating minimp3.h file to source and header

### ISSUE THREAD

**Issue by meet-marvell** [lieff/minimp3#30]
Hi,
First of all, thanks for the wonderful, low footprint and C based mp3 decoder you have developed for public domain.
My question is: **"Are you planning to separate minimp3.h into corresponding source files and header files in future according to their functionality?"**
That would be useful when analysing minimp3 as a standalone library component. For example: if I want to analyse the memory (flash + RAM) used by minimp3 on my controller, and if I have all components of minimp3 separated as .c and .h files, then I can create a different library for minimp3 using its own makefile and find out the text+RO data size, code size, RAM requirement etc. very easily. Apart from that, it will also improve the code organization, redability and understandibility.
Can you let me know if you are planning on it or not?

**Comment by lieff** [comment]
Thanks for the issue) Unfortunately at some point it's turned into single header and no plans to switch back. You can easily turn it in 2-files by adding following minimp3.c file:
```
/*Configuration:*/
/*#define MINIMP3_ONLY_MP3*/
/*#define MINIMP3_ONLY_SIMD*/
/*#define MINIMP3_NONSTANDARD_BUT_LOGICAL*/
#define MINIMP3_IMPLEMENTATION
#include "minimp3.h"
/*Or extended variant:
#define MINIMP3_NO_STDIO
#define MINIMP3_ALLOW_MONO_STEREO_TRANSITION
#include "minimp3_ex.h"
*/
```
I can calculate memory for embedded platforms without problems.

**Comment by meet-marvell** [comment]
Thanks for your help.
