### ISSUE TITLE
Track all of the binary files with git large file system.

### ISSUE THREAD

**Issue by tosone** [lieff/minimp3#31]
Lots of pcm bit mp3 files in this repo, we can track these file with git lfs now on GitHub.

**Comment by tosone** [comment]
Before:

![image](https://user-images.githubusercontent.com/5346506/44248167-90aeed80-a21b-11e8-834a-724d777fe6af.png)
![image](https://user-images.githubusercontent.com/5346506/44248175-9c021900-a21b-11e8-95db-7efc24a9aa01.png)

On master branch run this `git lfs migrate import --include-ref=master --include="*.mp3,*.bit,*.pcm,*.ttf,*.MP3,*.wav"`

![image](https://user-images.githubusercontent.com/5346506/44248187-afad7f80-a21b-11e8-9cc1-068f540ac3eb.png)

After:

![image](https://user-images.githubusercontent.com/5346506/44248199-c05df580-a21b-11e8-96b5-ab369339cf4f.png)

![image](https://user-images.githubusercontent.com/5346506/44248211-cc49b780-a21b-11e8-92b7-97f811407685.png)

Note: must push with force option.

I cannot push a repo that fork from yours. Because https://github.com/git-lfs/git-lfs/issues/1449#issuecomment-239831273.

So, new repo here: https://github.com/tosone/new-minimp3.

Git lfs doc: https://github.com/git-lfs/git-lfs/blob/master/docs/man/git-lfs-migrate.1.ronn

**Comment by lieff** [comment]
Wow, cool :) But unfortunately when I use standard git-lfs plugin - github do not recognize lfs files: https://github.com/lieff/minimp3/blob/master/vectors/ILL2_center2.bit
It seems their plugin store additional flag somewhere?

**Comment by lieff** [comment]
```
$ git lfs pull                                                                                                                           ↑
Git LFS: (0 of 0 files, 120 skipped) 0 B / 0 B, 22.09 MB skipped                                                                                                      [
fa9a4f4ab1e4dd8b2d08211d8c20a35c08237a0615172e8572d4b43645a9db2c] Object does not exist on the server: [404] Object does not exist on the server
[b750f748429ee011ede3ed03eb08b42c54d513d6a755737e422c3d951f7cc43f] Object does not exist on the server: [404] Object does not exist on the server
```
Github and standard versions incompatible? I cant force users to use github version.

**Comment by lieff** [comment]
Hmm, from you repo standard git lfs pull works fine. So, it some git lfs push to github issue.

**Comment by lieff** [comment]
Seems this issue https://github.com/git-lfs/git-lfs/issues/395

**Comment by lieff** [comment]
I export files back. So, can't use it right not - not stable enough.
