### ISSUE TITLE
How to perform sample-precision seeking?

### ISSUE THREAD

**Issue by djphoenix** [lieff/minimp3#38]
I'm implementing chunked decoding of mp3 files (for now they're decoding in a single float buffer, that produces ~1Gb PCM data for ~50min mp3, so that's unacceptable for e.g. mobile devices).
I have implemented "keypoints" save during initial analysing (decoding entire file without PCM output so it's fast), saving a file and sample offset each ~30sec. But when I seek to file position and call `mp3dec_decode_frame`, it produces zero-length output for first mp3 data frame (the next frames decodes successfully), so this way is produces sound glitch each ~30sec.

**Comment by lieff** [comment]
This because of bit-reservoir. There also windowing effect, I suggest start from-middle decoding 2 frames earlier and discard it's data.

**Comment by djphoenix** [comment]
Oh, I see. When I start with previous frame and discarding its result, all seems OK. Thank you for suggestion.
