### ISSUE TITLE
Unnecessary code duplication?

### ISSUE THREAD

**Issue by JuanPotato** [lieff/minimp3#43]
Lines 398 and 402 are the same exact code `ba = ba_code_tab[get_bits(bs, ba_bits)];` calling a function without having the parameters changed at all. It doesn't look like the second one does anything special. 

https://github.com/lieff/minimp3/blob/master/minimp3.h#L398-L402

**Comment by lieff** [comment]
Sequential get_bits() returns data from input stream sequentially, so ba_code_tab[] index can differ.

**Comment by JuanPotato** [comment]
Oh man
