### ISSUE TITLE
miniaac?

### ISSUE THREAD

**Issue by incrediball** [lieff/minimp3#49]
Sorry, this is not an issue with minimp3 but I don't believe there is any other way to ask this question. I would like to use minimp3 on a project but there is no point unless AAC can be decoded as well. The FFmpeg source code for the AAC decoder looks a little terrifying and appears to be vastly more complex than minimp3 but then articles such as this [one](https://www.iis.fraunhofer.de/content/dam/iis/de/doc/ame/conference/AES-17-Conference_mp3-and-AAC-explained_AES17.pdf) do not given this impression. So, I was wondering if anyone can answer these questions:

1. Is decoding AAC actually much more complex than decoding mp3? And are the processing requirements (CPU, RAM, ROM) for decoding AAC much higher? (If so, then how much approximately?)
2. Are there any small open source AAC decoders available or in the pipeline?
3. Could minimp3 be extended to support AAC or is AAC too different?

**Comment by tosone** [comment]
[https://github.com/nothings/single_file_libs#audio](https://github.com/nothings/single_file_libs#audio) Just found this. Exclude AAC.

**Comment by lieff** [comment]
Hi :)

1. AAC LC not much slower, just more code. But full AAC support far more complex.
2. I did not find any.
3. Nope, too different.

There other problems:
1. AAC is patented too, and afaik still not expired.
2. There also better alternative to implement http://opus-codec.org/comparison/ . But opus is far more complex too.

**Comment by incrediball** [comment]
Thanks for the feedback. Yes, I did mean AAC LC. Is perhaps part of the reason why the FFmpeg decoder is so big and complex is because it supports other less common variations of AAC?

I would like to decode AAC because radio stations typically stream using AAC now. The MP3 ones tend to be less common and the other formats like Vorbis seem to be even less common. Opus wouldn't be of any use to me unless that would become more mainstream.

**Comment by lieff** [comment]
I'm not sure about popularity. My personal feelings that aac popular on Apple ecosystem and BlueRay discs. And that's it.
Not sure about radio stations, I've google some top and checked streams from browser versions and did not find any without mp3 support. Usually both aac and mp3 supported. For example: http://abclounge.radio.net/
``streamContentFormats: 'MP3, AAC',``

Also there very low meaning in only AAC LC decoder (opposite to encoder, which can have point in LC only). It's like H264 baseline only decoder, content which adapted not for low end hardware (i.e. all current personal computers) can't be decoded. Decoder must support all profiles.

Also opus is definitely the future. Modern browsers already support it https://caniuse.com/#feat=opus
webrtc also uses opus by default. So, put effort in aac currently useless.

**Comment by incrediball** [comment]
The goal is to implement TuneIn as a minimum so if I use that as an example, if I list only my local radio stations that support [mp3](http://opml.radiotime.com/Browse.ashx?c=local&formats=mp3) then I get 22 stations but none of them are the mainstream ones, mostly all small community or ethnic radio stations. If I list only my local stations that support [aac](http://opml.radiotime.com/Browse.ashx?c=local&formats=aac), I get 16 stations but they include all of the mainstream ones which people will demand support for. (Of all of the stations, there were only two that support both formats.) Of course this may be quite different in other regions, I provided the links so you can try it in your region if you're interested.

Querying for [Vorbis](http://opml.radiotime.com/Browse.ashx?c=local&formats=ogg) yields very few stations and I don't know what the format specifier for Opus is, if it is even supported. Therefore MP3 and AAC are the primary ones that I would like to support.

Regarding the supported profiles, I have previously used the VS1053b IC for this role and its documentation states "VS1053b decodes MPEG2-AAC-LC-2.0.0.0 and MPEG4-AAC-LC-2.0.0.0 streams, i.e. the low complexity profile with maximum of two channels can be decoded.". As far as I know, the IC was not unable to play any AAC stream from any particular radio station and since the goal is to just substitute the capabilities of the IC with a software decoder then that is all that I would be looking for.

**Comment by lieff** [comment]
Well, https://github.com/knik0/faad2 or https://github.com/mstorsjo/fdk-aac can be used then.

**Comment by incrediball** [comment]
OK, thanks for the help.
