### ISSUE TITLE
Decoding of the first frame

### ISSUE THREAD

**Issue by bckpkol** [lieff/minimp3#53]
When a frame following the first frame is decoded it uses the previous frame. How is the first frame decoded, and what is used instead of the previous frame?

**Comment by lieff** [comment]
mp3 have concept of bit-reservoir, i.e. frame can use unused tail bits (because encoder rate control fails to use all bits) for next frame. If first frame become unavailable, decoder can't decode second frame, but if it's still passed to decoder, bit-reservoir become full and decoder can decode 3-rd frame. The number of frames before should have 511 payload bytes in the worst case to completely fill the reservoir.

**Comment by bckpkol** [comment]
I was more interested in https://github.com/lieff/minimp3/blob/e9df0760e94044caded36a55d70ab4152134adc5/minimp3.h#L766. than in https://github.com/lieff/minimp3/blob/master/minimp3.h#L773. Your code is too obfuscated for me. You name the variables inconsistently making it impossible to type a var name and find all occurencies. Also if you create a struct you might have been passed pointer to that struct but you pass the fields what results in a complete mess.
I'm not going to re-implement all that stuff. Maybe I'll edit your code to make it more readable. Currently I have one more question. Imagine I don't have a MP3 file, but I wrote an utility that generates data that looks like a frame. Synthesizing a frame, I mean. Can I decode that frame *alone*, or do I need the previous frame? When I use the short mode, do I need previous granules to decode the next granule, or I can decode the granule alone?

**Comment by lieff** [comment]
ireg it's region counter, there up to 3 regions can have own Huffman table, decoding starts from gr_info->table_select[0] table (it's not necessarily zero).
Even if frame do not use bit-reservoir, first frame alone will be not in good shape because of filterbank must be feeded, 2nd frame+ will be in good enough shape.
You are right, this code is not optimized for reading but for small size (both code and binary) and performance and I'm not going to change that.

Note that canonical mpg123 have even more optimized Huffman: https://github.com/georgi/mpg123/blob/master/src/libmpg123/layer3.c#L706
For me it's even less understandable despite it have some comments.

If you are looking for mos understandable code, I think it's reference code "MPEG-2 Audio Simulation Software Distribution 10".

**Comment by bckpkol** [comment]
```
#include <iostream>

typedef unsigned char uchar;
typedef struct mp3_header{
    uchar sync1 : 8;
    uchar sync2 : 3;
    uchar mpegVer : 2;
    uchar mpegLayer : 2;
    bool notProtected : 1;
    uchar _bitrate : 4;
    uchar _samplerate : 2;
    bool padded : 1;
    bool privateBit : 1;
    uchar _stereo : 2;
    uchar _jStereo : 2;
    bool proprietary : 1;
    bool original : 1;
    uchar emphasis : 2;
    unsigned short getBitrate();
    unsigned short getSamplerate();
    bool isStereo();
} __attribute__((packed));

int main() {
    std::cout << sizeof(mp3_header) << std::endl; //4
    return 0;
}
```
Why the code can't be like that? Just cast a pointer of a frame to (mp3_header*) and get all the fancy stuff. Also, readability can be mixed with speed. Also I don't see a point in making headers smaller.
But if you think your code is small I gonna break your illusions. Your code *could* be some kilobytes smaller if you use packed structs like that. In fact, I'm going to fork you.

**Comment by lieff** [comment]
I'm not against using bitfields, but it must be tested with at least following compilers:
gcc5-8 (arm, aarch64, x86, x64, ppc, ppc64), clang6-7 (arm, aarch64, x86, x64), armcc (arm, aarch64), msvc 20013-2017 (arm, aarch64, x86, x64).

Code size must be roughly same or less, and profiling must not show slowdown.

Usually compiler do same `shift` + `and` operators, but back some years ago I've experienced that some compilers do silly things with bitfields and do not use it since then. There also problem with big endian vs little endian on some architectures\compilers and you do not know in what order bytes are mapped to memory. In decoders it's usually handled in one place - get_bits() and then you may not think about endian till output generation.

**Comment by lieff** [comment]
That's why minimp3 reads input by chars in get_bits. It's not very optimal, usually optimized decoders uses big machine word load and byte swap instruction if available for architecture.
But there problem when you map structure mp3_header sizeof(mp3_header)>sizeof(char) on input stream directly, so, you must properly handle it.

**Comment by bckpkol** [comment]
Did you say "But there's a problem when you map a structure mp3_header sizeof(mp3_header)>sizeof(char) on input stream directly, so, you must properly handle that problem."?

**Comment by sagamusix** [comment]
Bit fields are implementation-defined. If your compiler wants, it may choose a completely different bit packing layout than what you expect. Please don't make minimp3 rely on such implementation-defined behaviour, it's bound to fail on at least some obscure platforms where the current code works just fine.
`__attribute__ ((__aligned__ (1)))` is also dangerous especially when passing around pointers to data extracted from such a struct, because the extracted pointer no longer contains any alignment information, and the compiler is free to assume that the data is aligned naturally.

**Comment by lieff** [comment]
Yeah, I'm completely forgot that it's also implementation defined

>C99 6.7.2.1-11:An implementation may allocate any addressable storage unit large enough to hold a bit- field. If enough space remains, a bit-field that immediately follows another bit-field in a structure shall be packed into adjacent bits of the same unit. If insufficient space remains, whether a bit-field that does not fit is put into the next unit or overlaps adjacent units is implementation-defined. The order of allocation of bit-fields within a unit (high-order to low-order or low-order to high-order) is implementation-defined. The alignment of the addressable storage unit is unspecified.

RIP bit fields for minimp3 use-case then.

**Comment by bckpkol** [comment]
The mess in the code leads to bugs.
https://github.com/lieff/minimp3/blob/e9df0760e94044caded36a55d70ab4152134adc5/minimp3.h#L1626
should be
if (i + k + hdr_padding(mp3) + nextfb + HDR_SIZE > mp3_bytes ) break;
 if(!hdr_compare(mp3, mp3 + k + nextfb)) continue;

**Comment by bckpkol** [comment]
`RIP bit fields for minimp3 use-case then.`
AFAIK, the most compilers do alignment of bitfields if there's non-bitfield members.
So, if I specify uchar:8 instead of uchar, no alignment should be done. Presto!

**Comment by lieff** [comment]
There already more strict check `i + 2*k < mp3_bytes`, check inside the loop `i + k + nextfb + HDR_SIZE > mp3_bytes` - for corner cases and very low k numbers. So there no performance optimization in this break and it's incorrect, because next match can be valid.

100% RIP it's not because of alignment, but because of implementation defined bits location, even in uchar.

**Comment by bckpkol** [comment]
Next match? mp3_bytes seems to be filesize minus offset in bytes. So if i + k + hdr_padding(mp3) + nextfb + HDR_SIZE > mp3_bytes, it's EOF. There's nothing after EOF.

**Comment by bckpkol** [comment]
If you understand "implementation defined bits location" so well, could you please explain what deep meaning does this phrase have?

**Comment by sagamusix** [comment]
It means that the bits can be packed in any way that the compiler sees fit. Just because you tested for example three different compilers on x86 (or whatever) that behaved the same doesn't mean that on another platform, they will behave identically. In particular this part of the quote from the standard is important:

> allocation of bit-fields within a unit (high-order to low-order or low-order to high-order) is implementation-defined

On some non-x86 platforms it can be more optimal to pack the fields in reverse order (top to bottom rather than bottom to top). The compiler is free to do so. "I tested several compilers" is not a proof for the lack of a compiler that doesn't do something different.

**Comment by lieff** [comment]
Yes, next match is possible, because at each k position there padding possibilities 0, 1 and 4, next match can have different padding.

**Comment by bckpkol** [comment]
> An implementation may allocate any addressable storage unit large enough to hold a bit- field.
So any buffer that has equal or greater size than one bitfield can hold that bitfield. That doesn't mean anything because we have one great bitfield and it's first. C doesn't align first elements.

>  If enough space remains, a bit-field that immediately follows another bit-field in a structure shall be packed into adjacent bits of the same unit.
That means adjacent bitfields are one big bitfield, and they keep the same order.

>  **If insufficient space remains**, whether a bit-field that does not fit is put into the next unit or overlaps adjacent units is implementation-defined.
If? Well. I said in GCC and Clang an element is only put in the next unit if it does not specify how much bits does it take, and thus, does not belong to a bitfield. But "implementation-defined". So, if a bitfield already contains 7 bits, we can't know if the next 2 bits will be placed immediately or after 1 bit. But we can! assert(sizeof(typename)==x) is our friend.

> The order of allocation of bit-fields within a unit (high-order to low-order or low-order to high-order) is implementation-defined. The alignment of the addressable storage unit is unspecified.
Within. RIP. But not for me, because I'm not going to be cross-platform.
Or, maybe not. A unit is byte. Inside a byte, bits can be shifted left and right. There's no reason why one could be faster then another. Also, if of 5 elements taking the second would be faster than taking the fourth, it would be unfair. Of course, the first is only shifted and the last, if it's not the edge, is only AND-ed.
At the edge, LSBs are AND-ed and shifted, and MSBs are shifted only. If to do the opposite, the number will be multiplied by the power of 2. It does not matter how the number is actually stored.
So if "the order of allocation of bit-fields within a unit is implementation-defined", it's not because of speed.

**Comment by bckpkol** [comment]
How about:
`struct foo {
#ifdef BIG_ENDIAN_BITFIELDS
    unsigned x:5;
    unsigned y:3;
#else
    unsigned y:3;
    unsigned x:5;
#endif
};
`

**Comment by lieff** [comment]
Also note that there no point to optimize this loop when iterations count is low. But imagine this loop goes 1000-2000 iterations (till MAX_FREE_FORMAT_FRAME_SIZE). This case is good optimization candidate.
Most obvious I see to do something like that:
```
                    if (!hdr_compare(mp3, mp3 + k + nextfb) + (i + k + nextfb + HDR_SIZE > mp3_bytes))
                        continue;
```
i.e. make one branch instead of two, which can be measurable improvement in busy loop at least on x86/x64.
But this function even not shown in complex mp3's profile. For now main problem resides in L3_imdct36/L3_dct3_9 optimization.

**Comment by bckpkol** [comment]
So, if the loop reaches EOF it simply repeats before it reaches MAX_FREE_FORMAT_FRAME_SIZE. The part "i + 2*k < mp3_bytes - HDR_SIZE" guarantees that it stops after continue.
But that makes another problem. If there's break, the next statement is not executed too, so we have branching in both cases. || and && cause branching too, don't you know? | and & don't. The only difference is after a break, 
https://github.com/lieff/minimp3/blob/e9df0760e94044caded36a55d70ab4152134adc5/minimp3.h#L1620
is not executed. It skips directly to the
https://github.com/lieff/minimp3/blob/e9df0760e94044caded36a55d70ab4152134adc5/minimp3.h#L1633
There's no memory error but using break could save 3 branches after the EOF. The count of the branches while the loop is the same. The only thing - fusing it would make the code shorter with (almost) no affect on performance, because my version is faster only when the loop reaches EOF otherwise it's the same speed.

**Comment by bckpkol** [comment]
The rule - if only one of many is evaluated, there's branching. Otherwise there's not.

**Comment by bckpkol** [comment]
```

:0
//do something
cmp a b
je 0
cmp a c
jne 1
:1

```
Your code.
```
:0
cmp a c
jne 1
//do something
cmp a b
je 0
cmp a c
jne 0
:1
```

**Comment by lieff** [comment]
Yeah, something like that, there also many optimizations can be done. For example we can try to vectorize header search at k position, and skip up to 4-8bytes if header guaranteed not there. This is potentially most worth optimization for this function.
For example here optimized scan for '.' and '?' for http server:
```
static void parse_uri(const char *uri, char **ext, char **qstr, int len)
{
    *ext  = 0;
    *qstr = 0;
    for(int c = 0; c < len;)
    {
        int l;
        // check for '.'
        uint64_t val = *(uint64_t*)(uri + c);
        uint64_t val_sav = val; 
        if (unlikely( (((val ^ 0x002e002e002e002eull) & 0x00ff00ff00ff00ffull) - 0x0001000100010001ull) & 0xff00ff00ff00ff00ull ))
        {
            goto check;
        }
        val >>= 8;
        if (unlikely( (((val ^ 0x002e002e002e002eull) & 0x00ff00ff00ff00ffull) - 0x0001000100010001ull) & 0xff00ff00ff00ff00ull ))
        {
check:
            for (int i = 0; i < sizeof(uint64_t); i++)
            {
                if ((uri + c)[i] == '.')
                    *ext = (char*)uri + c + i + 1; else
                if ((uri + c)[i] == '?')
                {
                    len = c + i;
                    goto fin;
                }
            }
            goto cont; // no need check current qword for '?' - already checked
        }
        // check for '?'
        val = val_sav;
        if (unlikely( (((val ^ 0x003f003f003f003full) & 0x00ff00ff00ff00ffull) - 0x0001000100010001ull) & 0xff00ff00ff00ff00ull ))
        {
            if ((uri + c)[0] == '?')
                len = c; else
            if ((uri + c)[2] == '?')
                len = c + 2; else
            if ((uri + c)[4] == '?')
                len = c + 4; else
            if ((uri + c)[6] == '?')
                len = c + 6;
            val >>= 8;
            l = len;
            if (unlikely( (((val ^ 0x003f003f003f003full) & 0x00ff00ff00ff00ffull) - 0x0001000100010001ull) & 0xff00ff00ff00ff00ull ))
            {
                goto check2;
            } else
                goto fin;
        }
        val >>= 8;
        if (unlikely( (((val ^ 0x003f003f003f003full) & 0x00ff00ff00ff00ffull) - 0x0001000100010001ull) & 0xff00ff00ff00ff00ull ))
        {
check2:
            if ((uri + c)[1] == '?')
                l = c + 1; else
            if ((uri + c)[3] == '?')
                l = c + 3; else
            if ((uri + c)[5] == '?')
                l = c + 5; else
            if ((uri + c)[7] == '?')
                l = c + 7;
            if (l < len)
                len = l;
fin:
            *qstr = (char *)uri + len;
            break;
        }
cont:
        c += sizeof(uint64_t);
    }
}
```

**Comment by bckpkol** [comment]
Link, please - the code for "unlikely" is missing.

**Comment by lieff** [comment]
There no link, this is my unpublished code.
This macros for gcc/clang:
```
#define likely(x)       __builtin_expect(!!(x), 1)
#define unlikely(x)     __builtin_expect(!!(x), 0)
```
such macros is widely know trick to help compiler with branch decisions without Profile Guided Optimizations build.

**Comment by bckpkol** [comment]
!((val ^ 0x002e002e002e002eull) & 0x00ff00ff00ff00ffull) - isn't it faster?

**Comment by lieff** [comment]
Because most string without '.' and '?', so we scan and skip by 8bytes which not contains them and this is main branch. For 8bytes which contains them we take unlikely() branch ant take a closer look by bytes.

**Comment by bckpkol** [comment]
if val ^ 0x002e002e002e002eull) & 0x00ff00ff00ff00ffull is false then there's four dots.
- 0x0001000100010001ull) & 0xff00ff00ff00ff00ull is true if there's at least one dot.
unlikely means it's rather false.

**Comment by lieff** [comment]
Yes, "least one dot" condition expected to be zero __builtin_expect("least one dot", 0), i.e. "least one dot" is not expected. Nothing wrong here.

**Comment by bckpkol** [comment]
Your code
```
typedef struct
{
    const uint8_t *buf;
    int pos, limit;
} bs_t;
```
My code:
```
  typedef struct  {
        mp3header* buf;
        size_t sz;
        ushort len;
        //added
        ushort len_hint;
        bool synced;
    } mp3frame;
```
These structs were similar in the beginning but then I've added more fields. Funny I've implemented almost the same without even looking at bs_t.

**Comment by bckpkol** [comment]
```
    typedef struct  {
        mp3header* buf;
        slong sz;
        sshort len;
        sshort len_hint;
        bool synced;
    } mp3frame;
```
That is better. My code is written in such a way a size could be negative.

**Comment by bckpkol** [comment]
```
    if (HDR_IS_CRC(hdr))
    {
        get_bits(bs_frame, 16);
    }
```
So, it does not check CRC? That does nothing because bs_frame is unchanged.

**Comment by lieff** [comment]
No, it ignores CRC. There several reasons for it:

 * Reference code checks CRC only for layer 1&2.
 * There streams with invalid CRC in the wild.
 * CRC enabled by bit in header, so there 1/2 probability to pass/fail check on random garbage data.
 * It can be handled externally, so we may not include it in small decoder. Optional functions I_CRC_calc/II_CRC_calc can be grabbed from reference code.

**Comment by bckpkol** [comment]
Your mp3d_find_frame is 1366 bytes, my OO mp3frame_getNext is 1508.

**Comment by bckpkol** [comment]
Right. It ignores CRC, and that is obvious, but it does nothing with bs_frame. Am I correct?

**Comment by lieff** [comment]
Nope, it updates bs_frame->pos field.

**Comment by bckpkol** [comment]
"if ((bs->pos += n) > bs->limit)"
Never did anything like that. *dp++ is my favorite but I'm always looking in the reference before doing stuff like this. What does it mean?

**Comment by lieff** [comment]
This equivalent to
```
bs->pos += n;
if (bs->pos > bs->limit)
```

**Comment by bckpkol** [comment]
I do not update len alone. Pythonic way is to increment the pointer and decrement the length.

**Comment by bckpkol** [comment]
It's polymorphism.

```
    
    typedef struct {
        float pcm[MAX_FREE_FORMAT_FRAME_SIZE];
        sshort len;
    } pcm;
    
    typedef struct {
        float pcm[MAX_FREE_FORMAT_FRAME_SIZE>>1][2];
        sshort len;
    } stereo;
```

**Comment by lieff** [comment]
Yeah, I know that trick and use same idea detect float point structure: https://github.com/lieff/lvg/blob/master/swf/avm1.c#L100
But that's not so embedded project like minimp3, which target micro-controllers like ESP32.

**Comment by bckpkol** [comment]
https://pastebin.com/Dwf3c1gg
Checked by https://gist.github.com/bckpkol/c35e0a832f99f8228e5e2f2798f5bb0a

**Comment by bckpkol** [comment]
Um. Didn't know zero-length bitfiels are align commands and cannot have names.

**Comment by bckpkol** [comment]
And even a void takes 1 byte. RIP?

**Comment by lieff** [comment]
```
    uchar sync2 : 3;
    uchar sync1 : 8;
```
There no guarantee that this should be at end of structure for LE. Also note that sizeof(uint) can be != 4 for some architectures, especially micro-controllers + unit mentioned in standard can be anything. And also there more endian variants possible https://github.com/lieff/lvg/blob/master/swf/avm1.c#L150
Also this should be put in separate file to change L3_MPEG1/L3_STEREO macros and create several needed structure variants.
So I highly doubt it can help for single header and be roughly same code size. Get_bits approach is not very worse in terms of readability, It's also used in ffmpeg which do not have code size restrictions.

**Comment by bckpkol** [comment]
```
    bool notProtected : 1;
    uchar mpegLayer : 2;
    uchar mpegVer : 2;
    uchar sync2 : 3;
    uchar sync1 : 8;
```
Everything's okay there. Again, I wrote a Python script that checks the alignment for all probabilities of ifdefs.

**Comment by lieff** [comment]
I think bit-fields still can be used in such low-level code, but when you create and use bit-fields objects for internal structures and do not try assume it's structure for read/write in files etc. It just not worth it.

**Comment by bckpkol** [comment]
My solution is std::false_type but it's only C++.

**Comment by bckpkol** [comment]
https://stackoverflow.com/questions/13716913/default-value-for-struct-member-in-c

**Comment by bckpkol** [comment]
Maybe Nim?

**Comment by bckpkol** [comment]
```
class bitfield {
    public:
        bitfield(uchar* buf, uchar start, uchar bits);
        operator uint() const;
        bitfield& operator=(const uint& rhs);
        bitfield& operator+=(const uint& rhs);
        bitfield& operator-=(const uint& rhs);
        bitfield& operator*=(const uint& rhs);
        bitfield& operator/=(const uint& rhs);
        bitfield& operator%=(const uint& rhs);
        bitfield& operator&=(const uint& rhs);
        bitfield& operator|=(const uint& rhs);
        bitfield& operator^=(const uint& rhs);
        bitfield& operator<<=(const uint& rhs);
        bitfield& operator>>=(const uint& rhs);
        bool operator ==(const uint& rhs) const;
        bool operator !=(const uint& rhs) const;
        bool operator <(const uint& rhs) const;
        bool operator <=(const uint& rhs) const;
        bool operator >(const uint& rhs) const;
        bool operator >=(const uint& rhs) const;
    private:
        uchar* buf;
        ushort mask;
        uchar rshift;
        bitfield& operator=(const bitfield& rhs);
        bitfield& operator+=(const bitfield& rhs);
        bitfield& operator-=(const bitfield& rhs);
        bitfield& operator*=(const bitfield& rhs);
        bitfield& operator/=(const bitfield& rhs);
        bitfield& operator%=(const bitfield& rhs);
        bitfield& operator&=(const bitfield& rhs);
        bitfield& operator|=(const bitfield& rhs);
        bitfield& operator^=(const bitfield& rhs);
        bitfield& operator<<=(const bitfield& rhs);
        bitfield& operator>>=(const bitfield& rhs);
} ;
```
Still not implemented but looks promising.

**Comment by lieff** [comment]
I'm aware about Nim, but it's more like another scripting alternative for https://github.com/lieff/lvg/issues/1
Do not see how it may help minimp3.

**Comment by bckpkol** [comment]
https://gist.github.com/bckpkol/6ee072b504cf5cb9561f8bc77ff2d800

**Comment by bckpkol** [comment]
https://pastebin.com/61LTNf8G
Yet not everything is implemented. I'll be mostly copy-pasting from C version.

**Comment by bckpkol** [comment]
https://github.com/lieff/minimp3/blob/e9df0760e94044caded36a55d70ab4152134adc5/minimp3.h#L548
doesn't look right because of
https://github.com/lieff/minimp3/blob/e9df0760e94044caded36a55d70ab4152134adc5/minimp3.h#L583

**Comment by lieff** [comment]
This is tricky part to simplify scale factors reading. Only long types 0,1,3 uses scfsi bits and this bits must be cleared because garbage can be here which ignored by reference decoder, but simplified L3_read_scalefactors looks at them first.
There special test vectors which tests all modes, and test procedure should blow up is case of such errors.

**Comment by bckpkol** [comment]
I've optimized your parse_ext even more.
With -O3 it's the same, with -O1 mine is a little bit faster.
```
//parse_ext is a weird thing.
//it's only useful when MIME header is incomplete
typedef unsigned long ulong;
typedef unsigned int uint;
typedef unsigned short ushort;
typedef unsigned char uchar;
#define LONGS_ARE_LITTLE (((union { ulong x; uint c; }){1}).c)
#define INTS_ARE_LITTLE (((union { uint x; ushort c; }){1}).c)
#define SHORTS_ARE_LITTLE (((union { ushort x; uchar c; }){1}).c)
typedef struct {
#ifdef LONGS_ARE_LITTLE
    uint a;
    uint b;
#else
    uint b;
    uint a;
#endif
} uint2;
typedef struct {
#ifdef INTS_ARE_LITTLE
    ushort a;
    ushort b;
#else
    ushort b;
    ushort a;
#endif
} ushort2;
typedef struct {
#ifdef SHORTS_ARE_LITTLE
    uchar a;
    uchar b;
#else
    uchar b;
    uchar a;
#endif
} uchar2;

#define MINIMUM(x) (x.a<x.b?x.a:x.b)
#define CC(x) (*(uchar2*)&x)
#define SC(x) (*(ushort2*)&x)
#define IC(x) (*(uint2*)&x)
static void parse_uri_opt(const char *uri, char **ext, char **qstr, int len) {
    *ext  = 0;
    *qstr = 0;
    ulong* uri_opt=(ulong*)uri;
    ulong* end_opt=(ulong*)(uri+(len&(~7)));
    while(uri_opt<end_opt) {//5 jumps binary search
        ulong val=*uri_opt++;
        {
            //binary search
            ulong dot=val^0x3f3f3f3f3f3f3f3ful;
            uint dot2=MINIMUM(IC(dot));
            ushort dot3=MINIMUM(SC(dot2));
            if(!CC(dot3).a) {
                if(CC(SC(dot2).b).a) {
                    if(CC(SC(IC(dot).b).a).a) {
                        *qstr = ((char*)uri_opt) - 8;
                    } else {
                        *qstr = ((char*)uri_opt) - 4;
                    }
                } else {
                    if(CC(SC(IC(dot).b).b).a) {
                        *qstr = ((char*)uri_opt) - 6;
                    } else {
                        *qstr = ((char*)uri_opt) - 2;
                    }
                }
                uri_opt=((ulong*)(*qstr));
                val=*(uri_opt-1);
            } else if (!CC(dot3).b) {
                if(CC(SC(dot2).b).b) {
                    if(CC(SC(IC(dot).b).a).b) {
                        *qstr = ((char*)uri_opt) - 7;
                    } else {
                        *qstr = ((char*)uri_opt) - 3;
                    }
                } else {
                    if(CC(SC(IC(dot).b).b).b) {
                        *qstr = ((char*)uri_opt) - 5;
                    } else {
                        *qstr = ((char*)uri_opt) - 1;
                    }
                }
                uri_opt=((ulong*)(*qstr));
                val=*(uri_opt-1);
            }
        }
        {
            //binary search
            ulong dot=val^0x2e2e2e2e2e2e2e2eul;
            uint dot2=MINIMUM(IC(dot));
            ushort dot3=MINIMUM(SC(dot2));
            if(!CC(dot3).b) {
                if(CC(SC(dot2).a).b) {
                    if(CC(SC(IC(dot).a).b).b) {
                        *ext = ((char*)uri_opt);
                    } else {
                        *ext = ((char*)uri_opt) - 4;
                    }
                } else {
                    if(CC(SC(IC(dot).a).a).b) {
                        *ext = ((char*)uri_opt) - 2;
                    } else {
                        *ext = ((char*)uri_opt) - 6;
                    }
                }
            } else if (!CC(dot3).a) {
                if(CC(SC(dot2).a).a) {
                    if(CC(SC(IC(dot).a).b).a) {
                        *ext = ((char*)uri_opt) - 1;
                    } else {
                        *ext = ((char*)uri_opt) - 5;
                    }
                } else {
                    if(CC(SC(IC(dot).a).a).a) {
                        *ext = ((char*)uri_opt) - 3;
                    } else {
                        *ext = ((char*)uri_opt) - 7;
                    }
                }
            }
        }
        if(*qstr) return;
    }
    *qstr=(char*)(uri+len);
    char* uri_last=(uchar*)uri_opt;
    while(uri_last<*qstr) {
        uchar val=*uri_last++;
        if (val == '?')
        {
            *qstr=--uri_last;
            return;
        }
        if (val == '.')
            *ext = uri_last;
        
    }
}
```

**Comment by bckpkol** [comment]
That loop
https://github.com/lieff/minimp3/blob/e9df0760e94044caded36a55d70ab4152134adc5/minimp3.h#L414
is redundant.

**Comment by lieff** [comment]
Yes, scfsi bits can b zero in mp3 file.
And yes, sci->bitalloc change is necessary and used later in L12_dequantize_granule.
