### ISSUE TITLE
howto get the beginning and ending status in mp3dec_iterate()?

### ISSUE THREAD

**Issue by dodoma** [lieff/minimp3#55]
In my case, I need to know mp3 playing state(e.g. start to play, end to play), so how can I do this ?

maybe i need to modify mp3dec_iterate_buf()

**Comment by lieff** [comment]
If I understand question correctly:

Player should run mp3dec_iterate_buf in separate thread when user hit "Play".
When callback called several times, player can start play audio without waiting mp3dec_iterate_buf ending in separate thread. Player optionally can show decoding progress using offset (offset->file_size) in callback. Player structures can be accessed using callback user_data.

Player can store decoded raw data for future seek/pause/resume or, to save memory, it can only store offsets to build index from what point decoding can be resumed at which time. In that case player can hold decoding on mutex on pause or can abort decoding from callback using non-zero return code and restart mp3dec_iterate_buf from needed offset on resume.

**Comment by dodoma** [comment]
My fault, I should explain situation more clear:

I called 
```c
int mp3dec_iterate(const char *file_name, MP3D_ITERATE_CB callback, void *user_data);
```
In a seperated thread to play some file, Disable the "PLAY" button in the UI.

And, when the file play finished. I need someway to Enable the "PLAY" button again.

The *Enable* action should be trigger in the MP3D_ITERATE_CB callback function with the following prototype:
```c
typedef int (*MP3D_ITERATE_CB)(void *user_data, const uint8_t *frame, int frame_size, size_t offset, mp3dec_frame_info_t *info);
```

I can't  know the decoding progress with the offset parameter, if I don't know the whole mp3 file's size.

So, i change the  mp3dec_iterate_buf() as following:

```diff
@@ -171,8 +174,10 @@
         buf_size -= i;
         if (i && !frame_size)
             continue;
-        if (!frame_size)
+        if (!frame_size) {
+            callback(user_data, NULL, 0, 0, NULL);
             break;
+        }
         const uint8_t *hdr = buf;
         frame_info.channels = HDR_IS_MONO(hdr) ? 1 : 2;
         frame_info.hz = hdr_sample_rate_hz(hdr);
```

Now, I can check if the  *frame* parameter is NULL, I'm reach the ending of the mp3 file, then, *Enable* the "PLAY" button again in the UI.

It can work for me, but not so pretty i think.

**Comment by lieff** [comment]
Hmm, why not send same signal when mp3dec_iterate() ends?
```
mp3dec_iterate()
callback(user_data, NULL, 0, 0, NULL);
```
or even more direct way than add it in callback.

**Comment by dodoma** [comment]
It's a little more complex in truth environment:
I have a seperated thread to play mp3 files one by one(with a PLAYLIST). It's properly that stop current playing file and switch to play another one. So, I have a global variable *bool g_new_playlist* to indicate that the PLAYLIST is refreshed by user, the iterate callback must stop, like this:

```c
int my_callback(void *user_data, const uint8_t *frame, int frame_size, size_t offset,
                           mp3dec_frame_info_t *info)
{
    if (g_new_playlist) return 1;
    ....
}
```

But this will stop every mp3dec_iterate() immediately because every new playlist will set g_new_playlist to true in the business thread. So, I have a static local variable *static bool playing;* in my_callback() to indicate is the iterate already started, like this:

```c
int my_callback(void *user_data, const uint8_t *frame, int frame_size, size_t offset,
                           mp3dec_frame_info_t *info)
{
    static bool playing = false;

    if (playing && g_new_playlist) {
        playing = false;
        return 1;
    }

    if (!playing) {
        /* change status on the first frame */
        playing = true;
        m_new_playlist = false;
    }
    ...
    /* set playing to false when iterate file normal end*/
    ...
}
```
So, the question is how to set playing to false when iterate a mp3 file end normally.
As your suggest, I can do this after mp3des_iterate() ends, but I think it will be more pretty if I can do this in my_callback().

**Comment by lieff** [comment]
Yeah, both approaches are good. But I personally want to keep default one with less must-be-done checks in callback and guaranteed nonzero frame.

**Comment by dodoma** [comment]
ok, I'll use the default one without change the callback's parameters.
