### ISSUE TITLE
Checking for invalid input files

### ISSUE THREAD

**Issue by jpcima** [lieff/minimp3#56]
Hi. It was brought to my attention a minor issue recently: it's possible for `mp3dec_load` to return 0 for success, yet giving a result having zero channels.

The software user tried to open a junk file as sound sample, the channels=0 situation caused FPE shortly after the minimp3 decoding. While the workaround is trivial at my side, it may be better to handle this checking at library level.

https://github.com/linuxmao-org/Frontieres/blob/a1cdcdb6b4531efca4f83f0483b08926134c4fc5/sources/model/Sample.cpp#L294-L300

Any files of text kind I sent into the decoder have resulted in the identical 0-channel situation. (readmes and such)

(on a side note, thanks for making the excellent library :+1:)

**Comment by lieff** [comment]
Yeah, this is definitely bug, thanks for reporting :)

**Comment by jpcima** [comment]
I checked in the latest into the project, and it worked fine. :+1:

**Comment by lieff** [comment]
Cool, glad to hear :)
