### ISSUE TITLE
Last frame + ID3v1 Tag

### ISSUE THREAD

**Issue by MangaD** [lieff/minimp3#57]
Hello, I am a newbie to this library and am facing a problem that I'm not sure if it is my fault or the library's fault. I am trying to get the position of the ID3v1 tag in the file, if it exists. I am using the following code - based on the example provided in this repository - to get info regarding an MP3 file:

https://pastebin.com/3gghY7L3
https://pastebin.com/2iQb5FTz

The problem I'm facing is that the ID3v1 position is not set where the `TAG` starts, but where the last frame starts, which seems to be caused by the function `mp3dec_decode_frame` returning 0 samples for the last frame when there is an ID3v1 tag in the MP3 file. Any help?

**Comment by MangaD** [comment]
Also don't forget the possibility of an enhanced tag being present:
https://en.wikipedia.org/wiki/ID3

**Comment by lieff** [comment]
Hello) Sorry for the delay.

There no need to check ID3v1 in decoding loop, you can do it at the same place ID3v2 is handled. Here sample of skipping ID3v1 https://github.com/lieff/minimp3/commit/6fc51c39f0f9b30421e9dc8994cd69f9a647f37b . If condition is true, tag position to parse will be buf + buf_size - 128. Note that unlike ID3v2, ID3v1 detection is not 100% safe, there possibility that "TAG" marker accidentally found in middle of real mp3 frame, so I put it under define.

**Comment by MangaD** [comment]
Hello! Thank you for the reply. Somehow I missed that define, erased it while adapting the code to my needs before realizing this problem. The odds of "TAG" being in a frame exactly at buf_size - 128 should be low so I'll take the risk. I changed the code a bit to support enhanced tags:
```cpp
	size_t id3v1size = 0;
#ifdef MINIMP3_SKIP_ID3V1
	if (buf_size > 128 && !strncmp((char *)buf + buf_size - 128, "TAG", 3)) {
		buf_size -= 128;
	        id3v1size += 128;
	        if (buf_size > 227 && !strncmp((char *)buf + buf_size - 227, "TAG+", 4)) {
	        	buf_size -= 227;
	        	id3v1size += 227;
	        }
	}
#endif
	info->id3v1size = id3v1size;
```

**Comment by lieff** [comment]
Oh, yes, I forgot about extended ID3v1 tag. I've add it here https://github.com/lieff/minimp3/commit/43caa38fbbae491d64ccfbde1cc1eb7686beec05 .
I did not find any software which writes it however, to make proper a test file.

**Comment by MangaD** [comment]
According to Wikipedia, the extended block is not an official standard and is only supported by few programs, not including XMMS or Winamp. So it is no big deal. I will close this issue now, thank you very much for your help!
