### ISSUE TITLE
Handle the invalid portion instead of sikpping

### ISSUE THREAD

**Issue by sinkpad** [lieff/minimp3#60]
Hi there,

Thank you for this great codec.

We have a mp3 file which contains one invalid portion. 

Checked by mp3val:
WARNING: "C:\work\software\mp3val-0.1.8_with_frontend-0.1.1-bin-win32\bvstts.mp3" (offset 0x630): MPEG stream error, resynchronized successfully
WARNING: "C:\work\software\mp3val-0.1.8_with_frontend-0.1.1-bin-win32\bvstts.mp3": No supported tags in the file
INFO: "C:\work\software\mp3val-0.1.8_with_frontend-0.1.1-bin-win32\bvstts.mp3": 91 MPEG frames (MPEG 2 Layer III), no tags, CBR

We decoded it using minimp3 and found this invalid portion was simply skipped.
I am wondering is there a way to add some "repaired data"?

The following picture:
Track 1: Lame decoded result, fixed the invalid portion
Track 2: minimp3 decoded result, one portion sikkped around 0.35s

![window001](https://user-images.githubusercontent.com/650096/63562624-df126d00-c590-11e9-9238-21dbfba3ed6c.png)

The mp3 file: [bvstts.zip](https://github.com/lieff/minimp3/files/3532574/bvstts.zip)

Thanks.

**Comment by lieff** [comment]
Hello :) Thanks for the issue, I will look at it asap.

**Comment by lieff** [comment]
@sinkpad Can you try this patch?

```

**Comment by sinkpad** [comment]
@lieff  It works! Thank you so much :)

![window002](https://user-images.githubusercontent.com/650096/63663116-b63de200-c7f3-11e9-8b33-a76abfc8a39b.png)

**Comment by lieff** [comment]
Good to hear) You may also want to change MAX_FRAME_SYNC_MATCHES to 1-2, to relax sync procedure.

This file have garbage data between frames. For sync procedure it means some skip and reset in general case. I'll see what I can do to keep correct sync procedure and handle such case automatically.

**Comment by sinkpad** [comment]
That would be great. Please keep me updated on this, thanks.

**Comment by lieff** [comment]
Theoretically, we can allow one garbage block per MAX_FRAME_SYNC_MATCHES frames, but this require additional potentially expensive loop in mp3d_find_frame. So I prefer not to add it here, application can do own de-packetization using hdr_* helper functions without proper sync procedure (and sacrafice free format support).
