### ISSUE TITLE
A question about mp3dec_skip_id3

### ISSUE THREAD

**Issue by MinnowBin** [lieff/minimp3#61]
Thanks your great work.
I want abstract you lib as an API to caller who could send any length raw mp3 data to the decoder. There is a case that caller send data is not a complete frame or id3 data. To checking this case, I use
mp3dec_iterate_buf, but a problem occur. when i send a data less than id3 data length, the  mp3dec_skip_id3 will modify the buf_size to a value which is not 0 but less than 0, so, the program will run error. I add some log as follow:
send mp3dec_skip_id3, buf_size = 512
after call mp3dec_skip_id3,  buf_size = -609 (printf this value as %d)

Could you solve my question, Thank you.

**Comment by lieff** [comment]
Hello. Thanks for the issue)

This is definitely a bug. Check if https://github.com/lieff/minimp3/commit/f618f1d98ceef22c163ad210167f2a02c5916e17 fixes this.

**Comment by MinnowBin** [comment]
Thanks, it work fine!

**Comment by lieff** [comment]
Glad to hear)
