### ISSUE TITLE
MP3 DCT quant smooth?

### ISSUE THREAD

**Issue by zvezdochiot** [lieff/minimp3#62]
See https://github.com/ilyakurdyukov/jpeg-quantsmooth/issues/9

**Comment by lieff** [comment]
По дискуссии не очень понял. Все трюки с квантизацией обычно в енкодере, а декодер обязан работать as-is и соответствовать референсному, иначе он не стандартный. Хотя не стандартные штуки типа эквалайзера можно встроить.

Единственное, по упоменанию [Replay Gain](https://ru.wikipedia.org/wiki/ReplayGain), могу предположить, что дело тут не столько в кодке дело, сколько во всей аудио системе. Если информацию из APEv2 она не прочитала, то может, вместо сканирования файла, начнет делать оценку на ходу, громкость может начнять усиливать, - и привет клиппинг.

**Comment by ilyakurdyukov** [comment]
@zvezdochiot думает, что у MP3 есть способ улучшить качество, восстановив утерянную точность каких-то кэфиициентов. Но вроде там просто срезаются частоты.

Для JPEG при записи коэффициенты делятся на значения из таблицы квантизации `coef / quant`, где `coef % quant` - это потерянные данные, так как деление целочисленное.

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>думает, что у MP3 есть способ улучшить качество

Чушь какая. Ничего подобного. Я думаю, что можно снизить шумы квантования для MP3, так же как это было сделано для JPEG в `jpeg-quantsmooth`. Это не "улучшит" звук, а сделает его "обрабатываемым".

**Comment by zvezdochiot** [comment]
@lieff say:
>могу предположить

Не надо предполагать, достаточно спросить. REPLAY_GAIN упоянут потому, что без него на нынешних MP3-шках наблюдается достаточно "жёсткий" клиппинг. Его то я и хочу использовать для построения модели деквантования (всё лучше и надёжнее, чем возиться с банком фильтров). У @ilyakurdyukov уже проработаны механизмы подавления шумов квантования, ему надо только помочь разобраться с самим MP3.

**Comment by ilyakurdyukov** [comment]
> REPLAY_GAIN упомянут потому, что без него
То есть тебе просто нужно найти максимальный сэмпл в записи и установить REPLAY_GAIN так, чтобы он равнялся допустимому максимуму?

> уже проработаны механизмы подавления шумов квантования
Изображения и звук - достаточно разные вещи.

> ему надо только помочь разобраться с самим MP3
А кто сказал, что я хочу этим заниматься? В принципе, вот этот проект хорошая стартовая точка. Только мне не настолько интересно, чтобы формат изучать ради этого.

**Comment by lieff** [comment]
То-есть, что-то типа шумодава встроенного в декодер?
Тогда это здесь https://github.com/georgi/mpg123/blob/master/src/libmpg123/layer3.c#L706 или в minimp3 здесь https://github.com/lieff/minimp3/blob/master/minimp3.h#L766 и придется помучаться с разными типами блоков. JPEG в этом плане проще. Так же в аудио обычно используют window, так что c блочными артефактами на границе борьба уже есть (для jpeg например есть еще https://github.com/google/knusperli, потому что в стандарте deblocking фильра не предусмотрено).

**Comment by zvezdochiot** [comment]
@ilyakurdyukov say:
>То есть тебе просто нужно

Нет. Мне нужно, зная что исходный звук был в пределах заданной битности (16бит, например), по клиппингу (коэффиценты DCT в данном случае априори неверны) построить модель, с учётом того, что средняя громкость исходного звука и MP3-шки равны. 

@ilyakurdyukov say:
>А кто сказал, что я хочу этим заниматься?

Никто. Я лишь указал возможный вариант применения ТВОИХ наработок. А уж чем заниматься на ГИТе - это каждый решает для себя сам.

@lieff say:
>придется помучаться с разными типами блоков.

Я так и знал, что где то прячется ж..па.

**Comment by zvezdochiot** [comment]
А я так хотел избавиться от шумов.
