### ISSUE TITLE
Extract unquantized MDCT frames

### ISSUE THREAD

**Issue by faroit** [lieff/minimp3#64]
For machine learning applications where models learn on spectral input representations, it would be handy to be able to load the unquantized MDCT frames without full decoding. That why audio loading speed can be greatly reduced.

How could this be achieved using minimp3?

**Comment by lieff** [comment]
Unquantized coefficients generated here https://github.com/lieff/minimp3/blob/master/minimp3.h#L766 , but it's hard to use because of different block types (and can't be extracted using API). But if you need only overall spectrum, you can use this draft code https://github.com/lieff/minimp3/blob/master/player/decode.c#L17 which I plan to use for visualization.

**Comment by faroit** [comment]
> But if you need only overall spectrum, you can use this draft code https://github.com/lieff/minimp3/blob/master/player/decode.c#L17 which I plan to use for visualization.

thanks for the pointer. This would be sufficient for classification tasks or ASR. But for enhancement, denoising, separation we would require to hook into the decoding pipeline to e.g. apply masking of the frames before decoding. E.g. see the following pseudo example:

```
mdct_frame = load_single_frame(path, seek)
processed_mdct_frame = model(mdct_frame)
out = imdct_decoding(processed_mdct_frame)
...
```

> Unquantized coefficients generated here https://github.com/lieff/minimp3/blob/master/minimp3.h#L766 , but it's hard to use because of different block types (and can't be extracted using API). 

would be great if this could be added to the api

**Comment by lieff** [comment]
>would be great if this could be added to the api

It can't, grbuf is located in scratch buffer and also will be overwritten when next granule is decoded. So it should be stored in decoder structure which increases decoder memory requirements. I think it should be modified and hooked here https://github.com/lieff/minimp3/blob/master/minimp3.h#L1178 for this specific task.

**Comment by faroit** [comment]
okay, thanks again. will have a look. Feel free to close this out.

**Comment by lieff** [comment]
Glad to help :)
