### ISSUE TITLE
Possible optimization for mp3d_scale_pcm on ARM

### ISSUE THREAD

**Issue by zephray** [lieff/minimp3#68]
On ARMv6+, the instruction SSAT can be used for clamping. By using the following code, based on my test, yields around 9~10% overall speed improvement on Cortex-M33 with GCC 8.3.1 -O3 with some 128Kbps MP3 files.

Obviously, this approach assumes that the value can fit in int32_t, otherwise it wouldn't work.

```c
static inline int16_t mp3d_scale_pcm(float sample)
{
    int32_t s32 = (int32_t)(sample + .5f);
    s32 -= (s32 < 0);
    int16_t s = (int16_t)__SSAT(s32, 16);
    return s;
}
```

**Comment by lieff** [comment]
Looks cool, I will try it ASAP)

**Comment by lieff** [comment]
Unfortunately I have trouble using this intrinsic with generic gcc builds from ubuntu/debian. There no __SSAT/__ssat/__builtin_arm_ssat, only clang have arm_acle.h with such intrinsic.
I tried to use helper function:

```
#if defined(__ARM_ARCH) && (__ARM_ARCH >= 6) && !defined(__aarch64__)
#define HAVE_ARMV6 1
static int32_t minimp3_clip_int16_arm(int32_t a)
{
    int32_t x;
    __asm__ ("ssat %0, #16, %1" : "=r"(x) : "r"(a));
    return x;
}
#endif
```

But it crashes qemu for some reason, so I cant test it. Arm64 also lack this instruction.

**Comment by zephray** [comment]
Yeah, it seems like it is not present in A64 instruction set. I will try on my ARMv7 machine to see if it works. On my platform (ARMv8M with arm-none-eabi-gcc), __ARM_ARCH is defined to be 8, but __aarch64__ is not defined so that detection should work fine.

**Comment by lieff** [comment]
```
0x00008bc4:  e6af2012      ssat r2, #16, r2
0x00008bc8:  e6af3013      ssat r3, #16, r3
0x00008bcc:  e1c030b0      strh r3, [r0]
0x00008bd0:  e18020b1      strh r2, [r0, r1]
0x00008bd4:  e49df004      pop  {pc}            ; (ldr pc, [sp], #4)

----------------
IN: mp3d_synth_granule
0x0000956c:  e28a2f7d      add  r2, sl, #500    ; 0x1f4
0x00009570:  e1a0100b      mov  r1, fp
0x00009574:  e59d0038      ldr  r0, [sp, #56]
0x00009578:  ebfffd34      bl   0x8a50

----------------
IN: mp3d_synth_granule
0x0000957c:  e28a20f0      add  r2, sl, #240    ; 0xf0
0x00009580:  e1a0100b      mov  r1, fp
0x00009584:  e1a00007      mov  r0, r7
0x00009588:  ebfffd30      bl   0x8a50

----------------
IN: mp3d_synth_granule
0x0000958c:  e1a0100b      mov  r1, fp
0x00009590:  e28a2e1f      add  r2, sl, #496    ; 0x1f0
0x00009594:  e59d003c      ldr  r0, [sp, #60]
0x00009598:  ebfffd2c      bl   0x8a50

qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
```
Looks like this issue not related with ssat changes but just bug in recent gcc (or new code generation triggers bug in qemu).
Qemu crashes with original code too on stack access but works fine in travis CI.

**Comment by lieff** [comment]
Yep https://github.com/lieff/minimp3/commit/60fd217a7e76f72bd552b70c04a29a8f6301940e passes the tests.

**Comment by lieff** [comment]
I assume can be closed? Feel free to reopen if needed.
