### ISSUE TITLE
Not able to load valid(?) minimal mp3

### ISSUE THREAD

**Issue by geokala** [lieff/minimp3#69]
I'm trying to test a library I'm working on with a minimal generated mp3 with id3v2 tags: https://github.com/geokala/korama/blob/master/resources/test/library/ignored.mp3

From looking at mp3 specs I believe the file to be a valid mp3, and it is treated as such by at least mpg123.
The mp3 is tagged with ID3v2.

However, it seems like minimp3 is failing to decode it- it gives the same output trying to parse it as it gives trying to parse minimp3's README.md.

Is this a problem with the file, with the use of ID3v2 tags, or with minimp3?

**Comment by lieff** [comment]
This file contains one mp3 frame. Problem is - this is free format frame, i.e. hdr_bitrate_kbps(h) == 0.
Minimum two free format frame needed to properly detect frame length, here it happens https://github.com/lieff/minimp3/blob/master/minimp3.h#L1669 .
If this loop fails we can treat it as such loose one free format frame. But it can be cut frame or false positive in data chunk. So for strong sync procedure we need at least 2 free format frames.

**Comment by geokala** [comment]
OK, thanks for the pointer- seems like it fails unless I have at least 4 frames, so I'll add three more frames to each test file.

Thanks!

**Comment by lieff** [comment]
@geokala Can you share vector with 3 free format frames? Theoretically minimp3 sync should work with 3 frames: 2 to detect length + 1 next to check detect is good.

**Comment by geokala** [comment]
OK, looks like you're right- not sure how I missed that three frames works.

I generated them using a small python script: https://gist.github.com/geokala/72e9bf3a42a98f4ed6a0a6896109e209

**Comment by lieff** [comment]
Ah, thanks) Everything working as expected then. I've add clarification to readme: https://github.com/lieff/minimp3/commit/82124b44babae68b83dd8e36ba9f35b76bd009b8

**Comment by geokala** [comment]
Looks great!
