### ISSUE TITLE
mp3dec_load() - block of zero samples in data (LAME mp3 with encoder delay)

### ISSUE THREAD

**Issue by dataflowg** [lieff/minimp3#71]
When using `mp3dec_load()` to read a LAME encoded mp3, there is a small block of samples near the start of the decoded data which is zero. The zero sample block is always appears between buffer[24] to buffer[46]. Otherwise the audio data is correct and the sample length is accurate with LAME's encoder delay.

mp3s were encoded with foobar2000 and LAME 3.99r. I also tested CBR 320 and VBR V0 with the same result.

[example_mp3s.zip](https://github.com/lieff/minimp3/files/4828998/example_mp3s.zip)

![mp3dec_load_zero](https://user-images.githubusercontent.com/44384905/85651218-f16ca400-b696-11ea-81df-590154c79915.png)

**Comment by lieff** [comment]
Hi :) Thanks for the issue, I will look at it asap.

**Comment by lieff** [comment]
Should be fixed in https://github.com/lieff/minimp3/commit/30b3a2c82db22e44acccb8c92fa3ce77f0be0ef5.
Thanks for catching that)

**Comment by dataflowg** [comment]
Thanks for such a quick fix :) Can confirm it's all working now 👍
![mp3dec_load_working](https://user-images.githubusercontent.com/44384905/85816731-b2eced00-b75b-11ea-9c3f-cf6e96cb0ff2.png)
