### ISSUE TITLE
How do you go about building codecs from scratch?

### ISSUE THREAD

**Issue by sincurve** [lieff/minimp3#79]
I apologize if this is not the right place to ask this but I see no way to contact you. Ho do you build codecs from scratch? Where did you find the necessary materials to learn the theoretical aspects of such complex technologies? I mean I have a decent background in dsp but even then the specs seem convoluted. Reference implementatios are too hard to study specially for beginners. I am a student doing research on Vorbis for my undergrad thesis and I would highly appreciate if you can guide me to the right path.

Thank you!

**Comment by lieff** [comment]
Hi)

I've place some useful links in readme https://github.com/lieff/minimp3#interesting-links .
That's not all, some links I've already forgot and some materials I've get long time ago on hdd and can't find any link for it.
For example I can't find https://github.com/lieff/mp3-enc-bsd anywhere already, so I create repo for it.

Reference code and specs sometimes is hard to understand, yes. And also it's usually slow.
That`s applies to other codecs too: ac3, aac, h264.

Open source usually takes several iterations to make it fast (and simpler in some places).
For mp3 you can check good open source implementations: ffmpeg, lame, mpg123.

For example compare this parts: 
https://github.com/lieff/minimp3/blob/master/minimp3.h#L778
https://github.com/sezero/mpg123/blob/master/src/libmpg123/layer3.c#L858

This is basically same Huffman decode + dequant. But note that mpg123 uses more unrolled style while minimp3 uses balance code size vs performance. Hmmm mpg123 do not use h->linbits == 0 case optimization, it may be slower.

That's all I can remember briefly, hope it helps)

**Comment by sincurve** [comment]
Thanks :)
