### ISSUE TITLE
Finding accurate track length by iterating using input buffer

### ISSUE THREAD

**Issue by rmsaad** [lieff/minimp3#81]
Hello, 

I haven't been using this library for very long so I am wondering if there is faster way to find track length than what I have done below. Currently it is way to slow to even be useful. 

```
while(1){
		bytesread = 0;
		samplesCount += mp3dec_decode_frame(&mp3d, (const uint8_t*) &input_data[0], MP3_BUF, 0, &info); 									
		memmove(&input_data[0], &input_data[info.frame_bytes], (MP3_BUF - info.frame_bytes));      											
		f_read(&FileRead, &input_data[MP3_BUF - info.frame_bytes], info.frame_bytes, (unsigned int*) &bytesread);  							
		
		if(bytesread == 0){																													
			while(info.frame_bytes){																											
				bufPos += info.frame_bytes;																										
				samplesCount += mp3dec_decode_frame(&mp3d, (const uint8_t*) &input_data[bufPos], MP3_BUF - bufPos, 0, &info);					
			}
		}
		if (info.frame_bytes <= 0) break;									
	}
	return samplesCount/info.hz;
```

**Comment by lieff** [comment]
Hi)

There is faster way if mp3 file contains vbr tag. You can use minimp3_ex to automatically use faster way:

```c
    mp3dec_ex_t dec;
    if (mp3dec_ex_open(&dec, input_file_name, MP3D_SEEK_TO_SAMPLE))
    {
        /* error */
    }
    /* dec.samples, dec.info.hz, dec.info.layer, dec.info.channels should be filled */
```

You also can use MP3D_DO_NOT_SCAN flag. In that case only fast way used, dec.samples is filled if vbr tag found and dec.samples == 0 otherwise.

**Comment by rmsaad** [comment]
Thanks for the quick reply. 

Unfortunately I am working on embedded project where the mp3s are stored on a USB(FATFS), the file handling functions in minimp3_ex.h do not work.

**Comment by lieff** [comment]
You can try minimp3_ex with MINIMP3_NO_STDIO and use mp3dec_ex_open_cb with custom io functions.

**Comment by rmsaad** [comment]
Thank you,

I will try that out , it seems like the best option.

**Comment by rmsaad** [comment]
Sorry again, 

Is there another way to read the vbr tag, I only have 128 KB of RAM and 64 KB of CCRAM to work with and the memory allocation in mp3dec_ex_open is returning MP3D_E_MEMORY error.

**Comment by rmsaad** [comment]
is it possible to make MINIMP3_IO_SIZE smaller?

**Comment by lieff** [comment]
Yes, try following config:

**Comment by rmsaad** [comment]
Thank you for your help,

It seems to be working now.

**Comment by rmsaad** [comment]
the *MINIMP3_NO_STDIO* mp3dec_ex_close() function does not free dec->file.buffer. I just copied that bit from the other close function, it seems to be freeing that memory now.

**Comment by lieff** [comment]
Thanks for catching this) Fixed in https://github.com/lieff/minimp3/commit/c02ef01e1211da8eaec974b43369a0817a866b94
