### ISSUE TITLE
Possible to get the index where the mp3 sample data starts?

### ISSUE THREAD

**Issue by mallgrab** [lieff/minimp3#83]
I'm using a c++ library ([libnyquist](https://github.com/ddiakopoulos/libnyquist)) which uses minimp3 to decode mp3 files.
Basically uses [mp3dec_load_buf ](https://github.com/ddiakopoulos/libnyquist/blob/fa4e1e37c3278aa3a9439f766e52e0b2db894c55/src/Mp3Decoder.cpp#L46)to decode the file.

The decoding is fine and its possible to find the sample data from the mp3 file but there's a huge amount of unnessary information which are floating numbers that are either just 0.00000 or above 1.0 or -1.0. The amount seems to increase with the length of the mp3 where if the mp3 only has 12 samples it would add an extra 2304 samples to the start. While if the mp3 is only 1 second long it would be around 6478 samples. The mp3 file is a 44100Hz 32-bit stereo file. libavcodec & LAME.

I've read that mp3 files tend to have extra delay added to them which contain encoding information which those extra samples probably are. But I was still curious if there's maybe a way to calculate the amount of samples you would have to jump to get to the actual sample data of the mp3.

**Comment by lieff** [comment]
Hi)

Looks like libnyquist uses old minimp3 when vbr tag still not implemented. Just update minimp3.h and minimp3_ex.h in 
libnyquist/third_party/minimp3/ and mp3dec_load_buf should use vbr tag information and produce exactly 12 samples with this file.

**Comment by mallgrab** [comment]
Wow that solved it, thanks! 👍
