### ISSUE TITLE
(lgtm static analysis) empty code blocks missing reasons

### ISSUE THREAD

**Issue by kcgen** [lieff/minimp3#86]
![Screenshot_20210119-112219_Brave](https://user-images.githubusercontent.com/1557255/105086409-d35cfb80-5a4d-11eb-993e-c068d39481ae.jpg)

@lieff, would you be able to drop a short comment in these two empty code blocks explaining / justification for why they're empty?

(This will help readers and also satisfy the analyzer) Thanks for the consideration.

**Comment by lieff** [comment]
Sure. Analyser wants comment inside block or outside works too?
```
@@ -1351,11 +1351,11 @@ static void mp3d_DCT_II(float *grbuf, int n)
             VSAVE4(3, t[3][7]);
         }
     } else
 #endif /* HAVE_SIMD */
 #ifdef MINIMP3_ONLY_SIMD
-    {}
+    {} /* for HAVE_SIMD=1, MINIMP3_ONLY_SIMD=1 case we do not need tail "else" branch */
 #else /* MINIMP3_ONLY_SIMD */
     for (; k < n; k++)
     {
         float t[4][8], *x, *y = grbuf + k;
``` 
Can you check if this works?

**Comment by kcgen** [comment]
Thanks, will do!

**Comment by kcgen** [comment]
Analysis underway here:
https://lgtm.com/projects/g/dosbox-staging/dosbox-staging/rev/pr-1fef07ba43bc337c135cfae6cbf1a757c2eaceb7

**Comment by lieff** [comment]
So it works, fixed in https://github.com/lieff/minimp3/commit/ef9e212fa29bb72d23558da21bb5694fd2d01768 .

**Comment by kcgen** [comment]
Thank you @lieff !
