### ISSUE TITLE
Samples format when channels>2.

### ISSUE THREAD

**Issue by nkrapivin** [lieff/minimp3#90]
Hello,
Imagine one decodes an MP3 for use with OpenAL-Soft.
The default (non-Soft) buffer formats are:
AL_FORMAT_MONO16 - Signed 16 Mono
AL_FORMAT_STEREO16 - Signed 16 Stereo
AL_FORMAT_MONO8 - Signed 8 Mono
AL_FORMAT_STEREO8 - Signed 8 Stereo

And as far as I understand, I need to use AL_FORMAT_MONO/STEREO16 most of the time (as the sample type is int16_t)

But what if the channel count is bigger than 2? What format should I use? Is there any documentation on it?

Thanks in advance.

**Comment by lieff** [comment]
Hi)
Mp3 format do not support channels>2. mp3dec_frame_info_t::channels can be only 1 or 2.

**Comment by nkrapivin** [comment]
Oh. Thanks!
