### ISSUE TITLE
Decode a file in chunks - is this code correct?

### ISSUE THREAD

**Issue by cgreening** [lieff/minimp3#91]
I'm having some trouble working out how to read a file in chunks and decode it - this is what I have so far and it doesn't seem to be working properly.

```c
  FILE *fp = fopen("test.mp3", "r");
  FILE *output = fopen("test.raw", "w");
  static mp3dec_t mp3d;
  mp3dec_init(&mp3d);
  short pcm[MINIMP3_MAX_SAMPLES_PER_FRAME];
  uint8_t input_buf[16384];
  mp3dec_frame_info_t info = {};
  while (1)
  {
    // keep reading until we run out of data
    size_t n = fread(input_buf, 1, 16384, fp);
    if (n == 0)
      break;
    // process the data
    int offset = 0;
    while (offset < n)
    {
      // decode the next frame
      int samples = mp3dec_decode_frame(&mp3d, input_buf + offset, n - offset, pcm, &info);
      if (samples > 0)
      {
        // write the decoded PCM samples
        fwrite(pcm, 1, samples * info.channels * sizeof(short), output);
      }
      // move past the decoded data
      offset += info.frame_bytes;
    }
  }
  fclose(output);
  fclose(fp);
```

**Comment by cgreening** [comment]
Ok, I see that I need to have a rolling buffer so that frames that go over the buffer boundaries are handled.

**Comment by lieff** [comment]
Yes, searching frames is one of the big complexity of mp3 format.

**Comment by 1AwesomeDeveloper** [comment]
> Ok, I see that I need to have a rolling buffer so that frames that go over the buffer boundaries are handled.

Hi, Can you please elaborate ?  I am stuck in an issue where my mp3dec_decode_frame() returns 1152 on first call and returns 0 on subsequent calls.
