### ISSUE TITLE
Different decoding results from ffmpeg and minimp3

### ISSUE THREAD

**Issue by wizardk** [lieff/minimp3#93]
Hi @lieff ,

In the [sample.zip](https://github.com/lieff/minimp3/files/7859307/sample.zip),
org.wav is the source audio.
org.wav was encoded to ffmpeg.mp3 by ffmpeg. 
ffmpeg.mp3 was decoded to ffmpeg.wav by ffmpeg.
ffmpeg.mp3 was decoded to minimp3.wav by minimp3. 

ffmpeg.wav and org.wav are very similar. minimp3.wav and org.wav are very different.

Do you know why?

**Comment by lieff** [comment]
Hi)
Sorry for late reply.
Is minimp3.wav decoded by minimp3 with own code or minimp3_ex?
I tried test application `./minimp3 ffmpeg.mp3 - out.wav` and it produces 5932 bytes, same as original.
So it looks like own code do not take into account vbr tag placed by ffmpeg.

**Comment by wizardk** [comment]
> Hi) Sorry for late reply. Is minimp3.wav decoded by minimp3 with own code or minimp3_ex? I tried test application `./minimp3 ffmpeg.mp3 - out.wav` and it produces 5932 bytes, same as original. So it looks like own code do not take into account vbr tag placed by ffmpeg.

Thanks for your answer. I used mp3dec_iterate_buf method to decode mp3.
I just retested and the result is:
mp3dec_load_buf is OK.
mp3dec_iterate_buf is NG.

**Comment by lieff** [comment]
That`s expected)
mp3dec_iterate_buf only iterates through mp3 frames.
So handling extensions like vbr tag is up to user code.

**Comment by wizardk** [comment]
> That's expected) mp3dec_iterate_buf only iterates through mp3 frames. So handling extensions like vbr tag is up to user code. That's why minimp3_ex exists in first place, because correct handling of all stuff is hand. Not like iterate through frames and call decode.

Thanks a lot.
