### ISSUE TITLE
Security Issue Report

### ISSUE THREAD

**Issue by schcamille** [lieff/minimp3#94]
Hello, we have discovered a bug with potential security impact within this project. Do you have a preferred security contact we could reach out to report this issue? Thank you very much!

**Comment by lieff** [comment]
Hi)
Hmm, maybe use Security Advisories? https://github.com/lieff/minimp3/security/advisories
"Privately discuss, fix, and publish information about security vulnerabilities in your repository's code."
It looks like the right thing for the case.

**Comment by schcamille** [comment]
Thanks! I think you need to be repo admin to create one (https://docs.github.com/en/code-security/security-advisories/about-github-security-advisories)

**Comment by lieff** [comment]
Yep, I think I created one, can you see it?

**Comment by schcamille** [comment]
Yes thanks!
